// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCGXsRGWNCFl171y1Ewcc-deFSNj_T5Qvs',
    appId: '1:96497259178:web:6a06592e4c645639a5f6d3',
    messagingSenderId: '96497259178',
    projectId: 'malaria-detector-82b86',
    authDomain: 'malaria-detector-82b86.firebaseapp.com',
    storageBucket: 'malaria-detector-82b86.firebasestorage.app',
    measurementId: 'G-RR8Y9CPY29',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCtbGwQWUYPCQbY-6FlhEhgdOf9SMvq9v4',
    appId: '1:96497259178:android:4ae70c23af82269fa5f6d3',
    messagingSenderId: '96497259178',
    projectId: 'malaria-detector-82b86',
    storageBucket: 'malaria-detector-82b86.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCGXsRGWNCFl171y1Ewcc-deFSNj_T5Qvs',
    appId: '1:96497259178:ios:6a06592e4c645639a5f6d3',
    messagingSenderId: '96497259178',
    projectId: 'malaria-detector-82b86',
    storageBucket: 'malaria-detector-82b86.firebasestorage.app',
    iosBundleId: 'com.example.malariaApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCGXsRGWNCFl171y1Ewcc-deFSNj_T5Qvs',
    appId: '1:96497259178:ios:6a06592e4c645639a5f6d3',
    messagingSenderId: '96497259178',
    projectId: 'malaria-detector-82b86',
    storageBucket: 'malaria-detector-82b86.firebasestorage.app',
    iosBundleId: 'com.example.malariaApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCGXsRGWNCFl171y1Ewcc-deFSNj_T5Qvs',
    appId: '1:96497259178:web:6a06592e4c645639a5f6d3',
    messagingSenderId: '96497259178',
    projectId: 'malaria-detector-82b86',
    authDomain: 'malaria-detector-82b86.firebaseapp.com',
    storageBucket: 'malaria-detector-82b86.firebasestorage.app',
    measurementId: 'G-RR8Y9CPY29',
  );
}
