// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyATsOmND_Ju2ZcTbwrXxvMybtEcm_RccQo',
    appId: '1:564371797028:web:213cab78e25f4eee7654b1',
    messagingSenderId: '564371797028',
    projectId: 'malaria-detection-48dc4',
    authDomain: 'malaria-detection-48dc4.firebaseapp.com',
    storageBucket: 'malaria-detection-48dc4.firebasestorage.app',
    measurementId: 'G-51QNVX965Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDi64FRvGvcIvsNqrq-tyS19oIQPllVBi0',
    appId: '1:564371797028:android:01cf2d8e892f75327654b1',
    messagingSenderId: '564371797028',
    projectId: 'malaria-detection-48dc4',
    storageBucket: 'malaria-detection-48dc4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAJUvRYiJghrTHbTLGTq9nRygpw53_ixRk',
    appId: '1:564371797028:ios:a1c14635905487007654b1',
    messagingSenderId: '564371797028',
    projectId: 'malaria-detection-48dc4',
    storageBucket: 'malaria-detection-48dc4.firebasestorage.app',
    iosBundleId: 'com.example.malariaApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAJUvRYiJghrTHbTLGTq9nRygpw53_ixRk',
    appId: '1:564371797028:ios:a1c14635905487007654b1',
    messagingSenderId: '564371797028',
    projectId: 'malaria-detection-48dc4',
    storageBucket: 'malaria-detection-48dc4.firebasestorage.app',
    iosBundleId: 'com.example.malariaApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyATsOmND_Ju2ZcTbwrXxvMybtEcm_RccQo',
    appId: '1:564371797028:web:16f00f228657152b7654b1',
    messagingSenderId: '564371797028',
    projectId: 'malaria-detection-48dc4',
    authDomain: 'malaria-detection-48dc4.firebaseapp.com',
    storageBucket: 'malaria-detection-48dc4.firebasestorage.app',
    measurementId: 'G-S2TNDQRKNC',
  );
}
